### ISSUE TITLE
Text for front page - suggestions

### ISSUE THREAD

**Issue by mialondon** [Living-with-machines/zoonyper#10]
For @mialondon to write: Something on the history/context of the project e.g. 
that it works with files exported from Zooniverse; 
that our interest has been in annotations (classifications (Zooniverse 'questions') or free text) on articles extracted from historical newspapers with article metadata included in the Zooniverse manifests; 
that our workflows have been built around the idea of winnowing out unsuitable or irrelevant articles then more detailed classsifications;
something on the composition of our subject sets (noting that they've changed over time)

For @kallewesterling to note - something on assumptions about how people will run it e.g. write their own python and import zoonyper to use the functions

**Comment by kallewesterling** [comment]
Text suggested here: https://github.com/Living-with-machines/zoonyper

**Comment by mialondon** [comment]
@kallewesterling can we do a 'coffee with Kalle' session working on the front page? It'd be great to really concretely describe what Zoonyper can do to Zooniverse files to encourage its uptake

Also the link to docs doesn't seem to go anywhere useful?
