### ISSUE TITLE
No module named 'wasabi'

### ISSUE THREAD

**Issue by mialondon** [Living-with-machines/zoonyper#13]
`from zoonyper import Project`

resulted in:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-6e3a44aac631> in <module>
----> 1 from zoonyper import Project

~/Zoonyper install/zoonyper/zoonyper/__init__.py in <module>
      1 __version__ = "0.1.0"
      2 
----> 3 from .project import Project

~/Zoonyper install/zoonyper/zoonyper/project.py in <module>
     12 import time
     13 
---> 14 from .utils import Utils, TASK_COLUMN, get_current_dir
     15 from .log import log
     16 

~/Zoonyper install/zoonyper/zoonyper/utils.py in <module>
      8 import re
      9 
---> 10 from .log import log
     11 
     12 

~/Zoonyper install/zoonyper/zoonyper/log.py in <module>
      1 # TODO: Make a better logger
      2 
----> 3 from wasabi import Printer
      4 
      5 printer = Printer()

ModuleNotFoundError: No module named 'wasabi'

**Comment by mialondon** [comment]
In a notebook, not a .py file, in case that makes a difference. The notebook was running in the zoonypter install folder.

**Comment by kallewesterling** [comment]
Wasabi is a prerequisite and should be installed by Poetry when setting up the Zoonyper installation.

**Comment by mialondon** [comment]
Ah, it might be a case of PEBKAC - I'd missed an install step, so wasabi wasn't actually the issue. 

I'm still dealing with Python 3.x issues.

**Comment by kallewesterling** [comment]
Never heard PEBKAC before!!
